# Statistics as LaTeX macros.
#
# Notebooks pass their numbers to the manuscripts only as \newcommand macros in
# a stats/*.tex file that main.tex \input's. `write_stats_tex()` writes such a
# file from a named list, checks that every name is a legal LaTeX command name
# (letters only, so \pilotNGames is fine and \pilotN2 is not), and refuses
# duplicates.
#
# Usage:
#   macros <- list()
#   macros <- c(macros, list(pilotNGames = n_games, pilotBetaLen = sprintf("%.3f", b)))
#   write_stats_tex(macros, file.path(prereg_dir, "stats", "pilot.tex"), source = "analysis/SI_pilot.qmd")
#
# Tests: analysis/tests/test_stats_tex.R

write_stats_tex <- function(macros, path, source = "an analysis notebook") {
  macros <- as.list(macros)
  nm <- names(macros)
  if (is.null(nm) || any(is.na(nm)) || any(nm == "")) {
    stop("write_stats_tex: every macro needs a name", call. = FALSE)
  }
  bad <- nm[!grepl("^[A-Za-z]+$", nm)]
  if (length(bad)) {
    stop(
      sprintf(
        "write_stats_tex: LaTeX command names may contain letters only: %s",
        paste(bad, collapse = ", ")
      ),
      call. = FALSE
    )
  }
  dup <- unique(nm[duplicated(nm)])
  if (length(dup)) {
    stop(
      sprintf(
        "write_stats_tex: duplicate macro names: %s",
        paste(dup, collapse = ", ")
      ),
      call. = FALSE
    )
  }
  values <- vapply(
    macros,
    function(v) {
      if (is.null(v) || length(v) == 0) {
        return("")
      }
      as.character(v)[1]
    },
    character(1)
  )
  lines <- sprintf("\\newcommand{\\%s}{%s}", nm, values)
  header <- sprintf("%% AUTO-GENERATED by %s -- do not edit by hand.", source)
  dir.create(dirname(path), showWarnings = FALSE, recursive = TRUE)
  writeLines(c(header, lines), path)
  cat("Wrote", length(lines), "macros to", path, "\n")
  invisible(path)
}

# Read the macro names defined in a stats file (for checks against main.tex)
stats_tex_names <- function(path) {
  lines <- readLines(path, warn = FALSE)
  m <- regmatches(lines, regexpr("\\\\newcommand\\{\\\\[A-Za-z]+\\}", lines))
  sub("\\\\newcommand\\{\\\\([A-Za-z]+)\\}", "\\1", m)
}


# Write pre-formatted "\\newcommand{\\name}{value}" lines (the SI notebooks build
# these with a small cmd() helper), with the same name checks as above.
write_stats_lines <- function(lines, path, source = "an analysis notebook") {
  nm <- sub("^\\\\newcommand\\{\\\\([^}]*)\\}.*$", "\\1", lines)
  bad <- nm[!grepl("^[A-Za-z]+$", nm)]
  if (length(bad)) {
    stop(sprintf("write_stats_lines: LaTeX command names may contain letters only: %s",
                 paste(bad, collapse = ", ")), call. = FALSE)
  }
  dup <- unique(nm[duplicated(nm)])
  if (length(dup)) {
    stop(sprintf("write_stats_lines: duplicate macro names: %s", paste(dup, collapse = ", ")), call. = FALSE)
  }
  header <- sprintf("%% AUTO-GENERATED by %s -- do not edit by hand.", source)
  dir.create(dirname(path), showWarnings = FALSE, recursive = TRUE)
  writeLines(c(header, lines), path)
  cat("Wrote", length(lines), "macros to", path, "\n")
  invisible(path)
}
