# Statistics as LaTeX macros.
#
# Notebooks pass their numbers to the manuscripts only as \newcommand macros in
# a stats/*.tex file that main.tex \input's. `write_stats_tex()` writes such a
# file from a named list, checks that every name is a legal LaTeX command name
# (letters only, so \pilotNGames is fine and \pilotN2 is not), and refuses
# duplicates.
#
# Usage:
#   macros <- list()
#   macros <- c(macros, list(pilotNGames = n_games, pilotBetaLen = sprintf("%.3f", b)))
#   write_stats_tex(macros, file.path(prereg_dir, "stats", "pilot.tex"), source = "analysis/SI_pilot.qmd")
#
# Tests: analysis/tests/test_stats_tex.R

write_stats_tex <- function(macros, path, source = "an analysis notebook") {
  macros <- as.list(macros)
  nm <- names(macros)
  if (is.null(nm) || any(is.na(nm)) || any(nm == "")) {
    stop("write_stats_tex: every macro needs a name", call. = FALSE)
  }
  bad <- nm[!grepl("^[A-Za-z]+$", nm)]
  if (length(bad)) {
    stop(
      sprintf(
        "write_stats_tex: LaTeX command names may contain letters only: %s",
        paste(bad, collapse = ", ")
      ),
      call. = FALSE
    )
  }
  dup <- unique(nm[duplicated(nm)])
  if (length(dup)) {
    stop(
      sprintf(
        "write_stats_tex: duplicate macro names: %s",
        paste(dup, collapse = ", ")
      ),
      call. = FALSE
    )
  }
  values <- vapply(
    macros,
    function(v) {
      if (is.null(v) || length(v) == 0) {
        return("")
      }
      as.character(v)[1]
    },
    character(1)
  )
  lines <- sprintf("\\newcommand{\\%s}{%s}", nm, values)
  header <- sprintf("%% AUTO-GENERATED by %s -- do not edit by hand.", source)
  dir.create(dirname(path), showWarnings = FALSE, recursive = TRUE)
  writeLines(c(header, lines), path)
  cat("Wrote", length(lines), "macros to", path, "\n")
  invisible(path)
}

# Read the macro names defined in a stats file (for checks against main.tex)
stats_tex_names <- function(path) {
  lines <- readLines(path, warn = FALSE)
  m <- regmatches(lines, regexpr("\\\\newcommand\\{\\\\[A-Za-z]+\\}", lines))
  sub("\\\\newcommand\\{\\\\([A-Za-z]+)\\}", "\\1", m)
}


# Write pre-formatted "\\newcommand{\\name}{value}" lines (the SI notebooks build
# these with a small cmd() helper), with the same name checks as above.
write_stats_lines <- function(lines, path, source = "an analysis notebook") {
  nm <- sub("^\\\\newcommand\\{\\\\([^}]*)\\}.*$", "\\1", lines)
  bad <- nm[!grepl("^[A-Za-z]+$", nm)]
  if (length(bad)) {
    stop(
      sprintf(
        "write_stats_lines: LaTeX command names may contain letters only: %s",
        paste(bad, collapse = ", ")
      ),
      call. = FALSE
    )
  }
  dup <- unique(nm[duplicated(nm)])
  if (length(dup)) {
    stop(
      sprintf(
        "write_stats_lines: duplicate macro names: %s",
        paste(dup, collapse = ", ")
      ),
      call. = FALSE
    )
  }
  header <- sprintf("%% AUTO-GENERATED by %s -- do not edit by hand.", source)
  dir.create(dirname(path), showWarnings = FALSE, recursive = TRUE)
  writeLines(c(header, lines), path)
  cat("Wrote", length(lines), "macros to", path, "\n")
  invisible(path)
}

# ── Building the macro lists ─────────────────────────────────────────────────
#
# The full-sample notebooks (00-05) each collect a named list of macros and
# write it with write_stats_tex() to stats_file("<notebook>") in the
# manuscript project (see config.R). Names are letters only and prefixed by
# the notebook (overview, checks, primary, secondary, exploratory, survey), so
# the six files can be \input together. Every estimate, confidence interval,
# p-value, and Bayes factor a notebook prints for a hypothesis goes through
# one of these helpers, so the manuscript never carries a hand-copied number.

fmt_stat <- function(x, digits = 3) {
  if (is.null(x) || length(x) == 0 || is.na(x)) {
    return("NA")
  }
  formatC(x, digits = digits, format = "f")
}

# A count, formatted with the LaTeX-safe thousands separator the SI uses
fmt_count <- function(n) {
  if (is.null(n) || length(n) == 0 || is.na(n)) {
    return("NA")
  }
  formatC(as.integer(round(n)), big.mark = "{,}", format = "d")
}

# The estimate, 95% CI, and p-value of one planned contrast as
# <prefix>Est, <prefix>Lo, <prefix>Hi, <prefix>P. `ct` is an emmeans contrast
# object or the table contrast_table() makes from one; `row` picks the
# contrast when the object holds several. A missing contrast gives no macros.
contrast_macros <- function(prefix, ct, row = 1L, digits = 3) {
  if (is.null(ct)) {
    return(list())
  }
  tab <- if (is.data.frame(ct) && "estimate" %in% names(ct)) {
    ct
  } else {
    contrast_table(ct, "")
  }
  if (is.null(tab) || nrow(tab) < row) {
    return(list())
  }
  r <- tab[row, ]
  setNames(
    list(
      fmt_stat(r$estimate, digits),
      fmt_stat(r$lower, digits),
      fmt_stat(r$upper, digits),
      fmt_pval(r$p.value)
    ),
    paste0(prefix, c("Est", "Lo", "Hi", "P"))
  )
}

# One fixed-effect coefficient of an lm, lmer (lmerTest), or glmer fit as
# <prefix>Est, <prefix>SE, <prefix>Stat (t or z), <prefix>P; a coefficient the
# model does not have gives no macros rather than an error.
coef_macros <- function(prefix, model, term, digits = 3) {
  if (is.null(model)) {
    return(list())
  }
  s <- coef(summary(model))
  if (is.null(s) || !term %in% rownames(s)) {
    return(list())
  }
  r <- s[term, ]
  stat_col <- intersect(c("t value", "z value"), names(r))
  p_col <- intersect(c("Pr(>|t|)", "Pr(>|z|)"), names(r))
  setNames(
    list(
      fmt_stat(r[["Estimate"]], digits),
      fmt_stat(r[["Std. Error"]], digits),
      if (length(stat_col)) fmt_stat(r[[stat_col[1]]], 2) else "NA",
      if (length(p_col)) fmt_pval(r[[p_col[1]]]) else "NA"
    ),
    paste0(prefix, c("Est", "SE", "Stat", "P"))
  )
}

# The Bayes factor of a bf_* result as <prefix>BF (three significant digits),
# or nothing when it was not computed
bf_macros <- function(prefix, bf) {
  if (is.null(bf) || is.null(bf$bf10) || is.na(bf$bf10)) {
    return(list())
  }
  setNames(
    list(formatC(bf$bf10, digits = 3, format = "g")),
    paste0(prefix, "BF")
  )
}
