# Tests for the stats-to-LaTeX writer in analysis/R/stats_tex.R.

if (!exists("write_stats_tex")) {
  source(here::here("analysis", "config.R"))
}
if (!exists("check")) {
  source(here::here("analysis", "tests", "check.R"))
}

tmp <- file.path(tempdir(), "stats_test", "pilot.tex")

path <- write_stats_tex(
  list(
    pilotNGames = 4,
    pilotBetaLen = sprintf("%.3f", -1.9691),
    note = "< .001"
  ),
  tmp,
  source = "test"
)
lines <- readLines(path)
check(
  "the file starts with the auto-generated header",
  grepl("^% AUTO-GENERATED by test", lines[1])
)
check(
  "each macro is a newcommand line",
  identical(
    lines[2:4],
    c(
      "\\newcommand{\\pilotNGames}{4}",
      "\\newcommand{\\pilotBetaLen}{-1.969}",
      "\\newcommand{\\note}{< .001}"
    )
  )
)
check(
  "stats_tex_names reads the names back",
  identical(stats_tex_names(path), c("pilotNGames", "pilotBetaLen", "note"))
)

err <- tryCatch(write_stats_tex(list(pilotN2 = 1), tmp), error = function(e) e)
check(
  "a macro name with a digit is rejected (LaTeX command names are letters only)",
  inherits(err, "error") && grepl("letters only", conditionMessage(err))
)
err <- tryCatch(write_stats_tex(list(a = 1, a = 2), tmp), error = function(e) e)
check(
  "duplicate macro names are rejected",
  inherits(err, "error") && grepl("duplicate", conditionMessage(err))
)
err <- tryCatch(write_stats_tex(list(1, 2), tmp), error = function(e) e)
check("unnamed macros are rejected", inherits(err, "error"))

# ── write_stats_lines (pre-formatted lines from the SI notebooks) ─────────────
tmp2 <- file.path(tempdir(), "stats_test", "lines.tex")
write_stats_lines(c("\\newcommand{\\pilotNGames}{4}", "\\newcommand{\\pilotNSig}{4}"), tmp2, source = "test")
check("write_stats_lines writes the header and the lines as given",
      identical(readLines(tmp2)[2:3], c("\\newcommand{\\pilotNGames}{4}", "\\newcommand{\\pilotNSig}{4}")))
err <- tryCatch(write_stats_lines("\\newcommand{\\pilotN2}{1}", tmp2), error = function(e) e)
check("write_stats_lines rejects a digit in a macro name", inherits(err, "error") && grepl("letters only", conditionMessage(err)))
